version: "3.9"

services:
  front:
    build:
      context: ./front
    container_name: front
    ports:
      - "80:3000"
    volumes:
      - ./front:/front
      - front_node_modules:/front/node_modules
    working_dir: /front
    stdin_open: true
    tty: true
    networks:
      - app-network

  deploy-service:
    build:
      context: ./deploy-service
    container_name: deploy-service
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - ./deploy-service:/deploy-service
    working_dir: /deploy-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  front_node_modules:
  deploy_service_node_modules:
