name: Front PROD (CRA → Nginx, multi-arch)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_POC }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_POC }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME_POC }}/front-poc
          tags: |
            type=raw,value=prod
            type=raw,value=latest
            type=sha

      - uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME_POC }}/front-poc:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME_POC }}/front-poc:buildcache,mode=max
